### ISSUE TITLE
Investigate why we don't seem to have logged data since October ...

### ISSUE THREAD

**Issue by rufuspollock** [openknowledge-archive/activityapi#20]
See e.g. http://activityapi.herokuapp.com/api/1/history/github

http://activityapi.herokuapp.com/api/1/history/mailman?grain=month&per_page=2

**Comment by rufuspollock** [comment]
OK so twitter stats are running: http://activityapi.herokuapp.com/api/1/history/twitter/account (and you can check this in the heroku logs ...)

**Comment by rufuspollock** [comment]
So fixed the github stuff - see b0b4fcdbfba8231ea0482cb48091880334123275 and previous

```
 heroku run ./scrape_github.py daily
```

Mailman stil needs fixing ...

**Comment by rufuspollock** [comment]
@zephod any update on this? I note that e.g. http://okfnlabs.org/dashboard/#project/schoolofdata only has stats up to September ...

**Comment by teajaymars** [comment]
Refactored and fixed
