### ISSUE TITLE
Twitter data no longer being pulled

### ISSUE THREAD

**Issue by rufuspollock** [openknowledge-archive/activityapi#24]
I note twitter shut off their old style API 1m+ ago.

Seems we are no longer getting up to date number for twitter follower counts etc.

**Comment by rufuspollock** [comment]
@zephod any thoughts ...

**Comment by teajaymars** [comment]
This is Twitter being needlessly high-maintenance:

```
zephod@localhost:~/code/activityapi$ heroku run "./snapshot_twitter.py"
Running `./snapshot_twitter.py` attached to terminal... up, run.8112
Traceback (most recent call last):
  File "./snapshot_twitter.py", line 60, in <module>
    main()
  File "./snapshot_twitter.py", line 57, in main
    snapshot_twitteraccounts(verbose=arg.verbose)
  File "./snapshot_twitter.py", line 29, in snapshot_twitteraccounts
    u = api.get_user(screen_name)
  File "/app/.heroku/python/lib/python2.7/site-packages/tweepy/binder.py", line 185, in _call
    return method.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/tweepy/binder.py", line 168, in execute
    raise TweepError(error_msg, resp)
tweepy.error.TweepError: [{u'message': u'The Twitter REST API v1 is no longer active. Please migrate to API v1.1. https://dev.twitter.com/docs/api/1.1/overview.', u'code': 68}]
```

I will switch it over to use https://github.com/bear/python-twitter, which requires it signs in with OAuth, which requires it has its own Twitter account, which requires it has its own email address, which I have just requested from sysadmin. :-)

**Comment by teajaymars** [comment]
There's a new Twitter account called `@activityapi` (usual password). The Heroku app signs in using OAuth to this account & scrapes data for everybody it is following. Dashboard graphs will start updating again hooray :)

**Comment by teajaymars** [comment]
I have pushed this to Heroku but can no longer push it to this Github repo due to diminished access rights.

To do this yourself:

```
git clone git@github.com:okfn/activityapi
cd activityapi
git remote add heroku git@heroku.com:activityapi.git
git pull --rebase heroku
git push origin
```

**Comment by rufuspollock** [comment]
@zephod you should have full access again - sorry about that (reorg of github teams recently!)

**Comment by teajaymars** [comment]
Cool, pushed, closing :-)
